### ISSUE TITLE
Critical program failure

### ISSUE THREAD

**Issue by tifu-mods** [ddevault/srutils#3]
Don't know what to say other than it just doesn't work. My bet is you haven't changed the program since reddit changed its API policy. Now you have to apply and shit.

```
C:\Users\XXXi>srutil --username the_dinks --password XXX duplicate /r/CrappyDesign /r/NouveauCrappyDesign
Logging in...
Resetting NouveauCrappyDesign to default settings...
Clearing CSS...

Unhandled Exception: System.Net.WebException: The remote server returned an error: (404) Not Found.
   at System.Net.HttpWebRequest.GetResponse()
   at RedditSharp.SubredditStyle.UpdateCss()
   at srutil.Reset.Execute(String[] args, Reddit reddit)
   at srutil.Duplicate.Execute(String[] args, Reddit reddit)
   at srutil.Program.Main(String[] args)
```

I tried it a few times, didn't work.

**Comment by lgarczyn** [comment]
I managed to avoid this error by simply commenting out parts of the backup functions, and replacing them with fake file in the zip file. It's a dirty fix but it works.

But yes, some subreddit don't have flairs, or css, and attempting to get them will yield a pretty 404 error that prevents the program from duplicating or saving the rest of the subreddit.
